package worker

import (
	"time"

	workeripc "github.com/cavos-io/rtp-agent/interface/worker/ipc"
	workerlivekit "github.com/cavos-io/rtp-agent/interface/worker/livekit"
)

var livekitServerRegisterWorkerMessage = workerlivekit.ServerRegisterWorkerMessage

var livekitServerAvailableWorkerStatusMessage = workerlivekit.ServerAvailableWorkerStatusMessage

var livekitServerDrainingWorkerStatusMessage = workerlivekit.ServerDrainingWorkerStatusMessage

var livekitServerJobStatusMessage = workerlivekit.ServerJobStatusMessage

var livekitServerJobRunningMessage = workerlivekit.ServerJobRunningMessage

var livekitServerMigrateRunningJobsMessage = workerlivekit.ServerMigrateRunningJobsMessage

var livekitExchangeInitialServerRegisterWebSocket = workerlivekit.ExchangeInitialServerRegisterWebSocket

var livekitRunServerMessageLoop = workerlivekit.RunServerMessageLoop

var livekitOpenServerWorkerWebSocket = workerlivekit.OpenServerWorkerWebSocket

var livekitRouteServerWorkerMessage = workerlivekit.RouteServerWorkerMessage

var livekitWriteServerWorkerMessageWebSocket = workerlivekit.WriteServerWorkerMessageWebSocket

var livekitAvailabilityInfo = workerlivekit.AvailabilityInfo

var livekitAnswerServerAvailabilityRequest = workerlivekit.AnswerServerAvailabilityRequest

var livekitStoreServerPendingAccept = workerlivekit.StoreServerPendingAccept

var livekitExpireServerPendingAccept = workerlivekit.ExpireServerPendingAccept

var livekitJobAssignmentInfo = workerlivekit.JobAssignmentInfo

func livekitAcceptServerPendingAssignment(
	pending map[string]JobAcceptArguments,
	timers map[string]*time.Timer,
	jobID string,
) (JobAcceptArguments, bool) {
	return workerlivekit.AcceptServerPendingAssignment(pending, timers, jobID)
}

var livekitJobTerminationInfo = workerlivekit.JobTerminationInfo

var livekitServerJobTerminationPlanForActiveJob = workerlivekit.ServerJobTerminationPlanForActiveJob

var livekitDefaultServerFakeLocalJobOptions = workerlivekit.DefaultServerFakeLocalJobOptions

var livekitPrepareServerLocalJobRunOptions = workerlivekit.PrepareServerLocalJobRunOptions

var livekitServerLocalJobExecutorPlan = workerlivekit.ServerLocalJobExecutorPlan

var livekitServerLocalJobSessionReportPath = workerlivekit.ServerLocalJobSessionReportPath

var livekitServerJobFinishPlan = workerlivekit.ServerJobFinishPlan

var livekitServerJobSessionReportUploadPlan = workerlivekit.ServerJobSessionReportUploadPlan

var livekitServerJobSessionEndPlan = workerlivekit.ServerJobSessionEndPlan

var livekitServerLocalJobContextSetupPlan = workerlivekit.ServerLocalJobContextSetupPlan

var livekitServerLogLevelFromEnv = workerlivekit.ServerLogLevelFromEnv

var livekitDefaultServerWorkerPermissions = workerlivekit.DefaultServerWorkerPermissions

var livekitResolveServerConnectionOptions = workerlivekit.ResolveServerConnectionOptions

var livekitWorkerRuntimeMetadata = workerlivekit.WorkerRuntimeMetadata

var livekitResolveServerAgentNameFromEnv = workerlivekit.ResolveServerAgentNameFromEnv

var livekitValidateServerConnectionOptions = workerlivekit.ValidateServerConnectionOptions

var livekitApplyServerConnectionEnv = workerlivekit.ApplyServerConnectionEnv

var livekitServerRunningJobInfoSnapshot = workerlivekit.ServerRunningJobInfoSnapshot

func livekitRunningJobInfoToIPC(info workerlivekit.RunningJobInfo) workeripc.RunningJobInfo {
	return workerlivekit.ToIPCRunningJobInfo(info)
}

func livekitRunningJobInfoFromIPC(info workeripc.RunningJobInfo) (workerlivekit.RunningJobInfo, error) {
	return workerlivekit.FromIPCRunningJobInfo(info)
}

func livekitRunningJobInfosFromIPC(infos []workeripc.RunningJobInfo) ([]workerlivekit.RunningJobInfo, error) {
	return workerlivekit.FromIPCRunningJobInfos(infos)
}

var livekitRefreshServerRunningJobsForReload = workerlivekit.RefreshServerRunningJobsForReload

var livekitServerReloadedJobContextValues = workerlivekit.ServerReloadedJobContextValues

var livekitServerRecordingOptions = workerlivekit.ServerRecordingOptions

var livekitServerRunningJobContextValues = workerlivekit.ServerRunningJobContextValues

var livekitRunServerRunningJobEntrypointLifecycle = workerlivekit.RunServerRunningJobEntrypointLifecycle

var livekitRunServerReloadedJobEntrypointLifecycle = workerlivekit.RunServerReloadedJobEntrypointLifecycle

var livekitServerMigratableRunningJobIDs = workerlivekit.ServerMigratableRunningJobIDs

var livekitServerAssignmentContextValues = workerlivekit.ServerAssignmentContextValues

var livekitRunServerJobEntrypointLifecycle = workerlivekit.RunServerJobEntrypointLifecycle
