package worker

import workerlivekit "github.com/cavos-io/rtp-agent/interface/worker/livekit"

var livekitJobContextInferenceHeaders = workerlivekit.JobContextInferenceHeaders

var livekitNewJobContextAPI = workerlivekit.NewJobContextAPI

var livekitNewJobContextSessionReport = workerlivekit.NewJobContextSessionReport

var livekitJobContextLogFields = workerlivekit.JobContextLogFields

var livekitJobContextParticipantIdentity = workerlivekit.JobContextParticipantIdentity

var livekitJobContextLocalParticipantIdentity = workerlivekit.JobContextLocalParticipantIdentity

var livekitJobContextTokenClaims = workerlivekit.JobContextTokenClaims

var livekitJobContextJobID = workerlivekit.JobContextJobID

var livekitPopulateJobContextSessionReport = workerlivekit.PopulateJobContextSessionReport

var livekitJobContextAvatarStartInfo = workerlivekit.JobContextAvatarStartInfo

var livekitJobContextRoom = workerlivekit.JobContextRoom

var livekitJobContextPublisher = workerlivekit.JobContextPublisher

var livekitJobContextLocalParticipant = workerlivekit.JobContextLocalParticipant

var livekitNewJobContextRoom = workerlivekit.NewJobContextRoom

var livekitJobContextNormalizeConnectOptions = workerlivekit.JobContextNormalizeConnectOptions

var livekitJobContextJoinPreparedRoom = workerlivekit.JobContextJoinPreparedRoom

var livekitJobContextRemoteParticipantViews = workerlivekit.JobContextRemoteParticipantViews

var livekitJobContextRoomName = workerlivekit.JobContextRoomName

var livekitJobContextApplyAutoSubscribeToRoom = workerlivekit.JobContextApplyAutoSubscribeToRoom

var livekitJobContextRoomCallbackWithHandlers = workerlivekit.JobContextRoomCallbackWithHandlers

var livekitJobContextParticipantInfoFromRemoteParticipant = workerlivekit.JobContextParticipantInfoFromRemoteParticipant

var livekitJobContextUpsertParticipantInfo = workerlivekit.JobContextUpsertParticipantInfo

var livekitJobContextParticipantEntrypointRegistrationPlan = workerlivekit.JobContextParticipantEntrypointRegistrationPlan

var livekitJobContextWaitForParticipant = workerlivekit.JobContextWaitForParticipant

var livekitJobContextWaitForAgent = workerlivekit.JobContextWaitForAgent

var livekitJobContextWaitForTrackPublication = workerlivekit.JobContextWaitForTrackPublication

var livekitJobContextWaitForTrackPublicationWithOptions = workerlivekit.JobContextWaitForTrackPublicationWithOptions

var livekitJobContextWaitForParticipantAttribute = workerlivekit.JobContextWaitForParticipantAttribute

var livekitJobContextParticipantEntrypointTaskPlan = workerlivekit.JobContextParticipantEntrypointTaskPlan

var livekitJobContextDeleteRoomPlan = workerlivekit.JobContextDeleteRoomPlan

var livekitJobContextDeleteRoomBestEffort = workerlivekit.JobContextDeleteRoomBestEffort

var livekitJobContextMoveParticipantPlan = workerlivekit.JobContextMoveParticipantPlan

var livekitJobContextMoveParticipant = workerlivekit.JobContextMoveParticipant

var livekitJobContextSIPCreateParticipantPlan = workerlivekit.JobContextSIPCreateParticipantPlan

var livekitJobContextCreateSIPParticipantWithNames = workerlivekit.JobContextCreateSIPParticipantWithNames

var livekitJobContextCreateSIPParticipantWithRequest = workerlivekit.JobContextCreateSIPParticipantWithRequest

var livekitJobContextSIPTransferParticipantPlan = workerlivekit.JobContextSIPTransferParticipantPlan

var livekitJobContextTransferSIPParticipantByParticipant = workerlivekit.JobContextTransferSIPParticipantByParticipant
