package worker

import workerlivekit "github.com/cavos-io/rtp-agent/interface/worker/livekit"

var livekitServerRegisterWorkerMessage = workerlivekit.ServerRegisterWorkerMessage

var livekitServerAvailableWorkerStatusMessage = workerlivekit.ServerAvailableWorkerStatusMessage

var livekitServerDrainingWorkerStatusMessage = workerlivekit.ServerDrainingWorkerStatusMessage

var livekitServerJobStatusMessage = workerlivekit.ServerJobStatusMessage

var livekitServerJobRunningMessage = workerlivekit.ServerJobRunningMessage

var livekitServerMigrateRunningJobsMessage = workerlivekit.ServerMigrateRunningJobsMessage

var livekitExchangeInitialServerRegisterWebSocket = workerlivekit.ExchangeInitialServerRegisterWebSocket

var livekitRunServerMessageLoop = workerlivekit.RunServerMessageLoop

var livekitOpenServerWorkerWebSocket = workerlivekit.OpenServerWorkerWebSocket

var livekitRouteServerWorkerMessage = workerlivekit.RouteServerWorkerMessage

var livekitWriteServerWorkerMessageWebSocket = workerlivekit.WriteServerWorkerMessageWebSocket

var livekitAvailabilityInfo = workerlivekit.AvailabilityInfo

var livekitAnswerServerAvailabilityRequest = workerlivekit.AnswerServerAvailabilityRequest

var livekitStoreServerPendingAccept = workerlivekit.StoreServerPendingAccept

var livekitExpireServerPendingAccept = workerlivekit.ExpireServerPendingAccept

var livekitServerLogLevelFromEnv = workerlivekit.ServerLogLevelFromEnv

var livekitDefaultServerWorkerPermissions = workerlivekit.DefaultServerWorkerPermissions

var livekitResolveServerConnectionOptions = workerlivekit.ResolveServerConnectionOptions

var livekitWriteWorkerRuntimeMetadataHTTPResponse = workerlivekit.WriteWorkerRuntimeMetadataHTTPResponse

var livekitResolveServerAgentNameFromEnv = workerlivekit.ResolveServerAgentNameFromEnv

var livekitValidateServerConnectionOptions = workerlivekit.ValidateServerConnectionOptions

var livekitApplyServerConnectionEnv = workerlivekit.ApplyServerConnectionEnv
