// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: smart_turn_service.proto

package spec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmartTurnServiceV1_Predict_FullMethodName = "/smart_turn.SmartTurnServiceV1/Predict"
)

// SmartTurnServiceV1Client is the client API for SmartTurnServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SmartTurnServiceV1 predicts turn-completeness from pre-extracted mel features.
// Plan A: Python runs WhisperFeatureExtractor and ships the mel spectrogram;
// Go runs ONNX inference only.
type SmartTurnServiceV1Client interface {
	Predict(ctx context.Context, in *SmartTurnRequest, opts ...grpc.CallOption) (*SmartTurnResponse, error)
}

type smartTurnServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewSmartTurnServiceV1Client(cc grpc.ClientConnInterface) SmartTurnServiceV1Client {
	return &smartTurnServiceV1Client{cc}
}

func (c *smartTurnServiceV1Client) Predict(ctx context.Context, in *SmartTurnRequest, opts ...grpc.CallOption) (*SmartTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmartTurnResponse)
	err := c.cc.Invoke(ctx, SmartTurnServiceV1_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartTurnServiceV1Server is the server API for SmartTurnServiceV1 service.
// All implementations must embed UnimplementedSmartTurnServiceV1Server
// for forward compatibility.
//
// SmartTurnServiceV1 predicts turn-completeness from pre-extracted mel features.
// Plan A: Python runs WhisperFeatureExtractor and ships the mel spectrogram;
// Go runs ONNX inference only.
type SmartTurnServiceV1Server interface {
	Predict(context.Context, *SmartTurnRequest) (*SmartTurnResponse, error)
	mustEmbedUnimplementedSmartTurnServiceV1Server()
}

// UnimplementedSmartTurnServiceV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmartTurnServiceV1Server struct{}

func (UnimplementedSmartTurnServiceV1Server) Predict(context.Context, *SmartTurnRequest) (*SmartTurnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedSmartTurnServiceV1Server) mustEmbedUnimplementedSmartTurnServiceV1Server() {}
func (UnimplementedSmartTurnServiceV1Server) testEmbeddedByValue()                            {}

// UnsafeSmartTurnServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartTurnServiceV1Server will
// result in compilation errors.
type UnsafeSmartTurnServiceV1Server interface {
	mustEmbedUnimplementedSmartTurnServiceV1Server()
}

func RegisterSmartTurnServiceV1Server(s grpc.ServiceRegistrar, srv SmartTurnServiceV1Server) {
	// If the following call panics, it indicates UnimplementedSmartTurnServiceV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmartTurnServiceV1_ServiceDesc, srv)
}

func _SmartTurnServiceV1_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmartTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartTurnServiceV1Server).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartTurnServiceV1_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartTurnServiceV1Server).Predict(ctx, req.(*SmartTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartTurnServiceV1_ServiceDesc is the grpc.ServiceDesc for SmartTurnServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartTurnServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smart_turn.SmartTurnServiceV1",
	HandlerType: (*SmartTurnServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _SmartTurnServiceV1_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smart_turn_service.proto",
}
