// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: smart_turn_service.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmartTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []byte                 `protobuf:"bytes,1,opt,name=features,proto3" json:"features,omitempty"`                     // mel spectrogram, float32 little-endian, mel-major flattened (mel_bins * time_steps)
	MelBins       int32                  `protobuf:"varint,2,opt,name=mel_bins,json=melBins,proto3" json:"mel_bins,omitempty"`       // n_mels (e.g. 80)
	TimeSteps     int32                  `protobuf:"varint,3,opt,name=time_steps,json=timeSteps,proto3" json:"time_steps,omitempty"` // n_frames (e.g. 800)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmartTurnRequest) Reset() {
	*x = SmartTurnRequest{}
	mi := &file_smart_turn_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmartTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartTurnRequest) ProtoMessage() {}

func (x *SmartTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smart_turn_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartTurnRequest.ProtoReflect.Descriptor instead.
func (*SmartTurnRequest) Descriptor() ([]byte, []int) {
	return file_smart_turn_service_proto_rawDescGZIP(), []int{0}
}

func (x *SmartTurnRequest) GetFeatures() []byte {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *SmartTurnRequest) GetMelBins() int32 {
	if x != nil {
		return x.MelBins
	}
	return 0
}

func (x *SmartTurnRequest) GetTimeSteps() int32 {
	if x != nil {
		return x.TimeSteps
	}
	return 0
}

type SmartTurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsComplete    bool                   `protobuf:"varint,1,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`     // probability >= threshold
	Probability   float32                `protobuf:"fixed32,2,opt,name=probability,proto3" json:"probability,omitempty"`                    // raw model output [0..1]
	InferenceMs   float32                `protobuf:"fixed32,3,opt,name=inference_ms,json=inferenceMs,proto3" json:"inference_ms,omitempty"` // inference time in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmartTurnResponse) Reset() {
	*x = SmartTurnResponse{}
	mi := &file_smart_turn_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmartTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartTurnResponse) ProtoMessage() {}

func (x *SmartTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smart_turn_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartTurnResponse.ProtoReflect.Descriptor instead.
func (*SmartTurnResponse) Descriptor() ([]byte, []int) {
	return file_smart_turn_service_proto_rawDescGZIP(), []int{1}
}

func (x *SmartTurnResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *SmartTurnResponse) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *SmartTurnResponse) GetInferenceMs() float32 {
	if x != nil {
		return x.InferenceMs
	}
	return 0
}

var File_smart_turn_service_proto protoreflect.FileDescriptor

const file_smart_turn_service_proto_rawDesc = "" +
	"\n" +
	"\x18smart_turn_service.proto\x12\n" +
	"smart_turn\"h\n" +
	"\x10SmartTurnRequest\x12\x1a\n" +
	"\bfeatures\x18\x01 \x01(\fR\bfeatures\x12\x19\n" +
	"\bmel_bins\x18\x02 \x01(\x05R\amelBins\x12\x1d\n" +
	"\n" +
	"time_steps\x18\x03 \x01(\x05R\ttimeSteps\"y\n" +
	"\x11SmartTurnResponse\x12\x1f\n" +
	"\vis_complete\x18\x01 \x01(\bR\n" +
	"isComplete\x12 \n" +
	"\vprobability\x18\x02 \x01(\x02R\vprobability\x12!\n" +
	"\finference_ms\x18\x03 \x01(\x02R\vinferenceMs2\\\n" +
	"\x12SmartTurnServiceV1\x12F\n" +
	"\aPredict\x12\x1c.smart_turn.SmartTurnRequest\x1a\x1d.smart_turn.SmartTurnResponseB2Z0github.com/cavos-io/grpc-llm/interface/grpc/specb\x06proto3"

var (
	file_smart_turn_service_proto_rawDescOnce sync.Once
	file_smart_turn_service_proto_rawDescData []byte
)

func file_smart_turn_service_proto_rawDescGZIP() []byte {
	file_smart_turn_service_proto_rawDescOnce.Do(func() {
		file_smart_turn_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smart_turn_service_proto_rawDesc), len(file_smart_turn_service_proto_rawDesc)))
	})
	return file_smart_turn_service_proto_rawDescData
}

var file_smart_turn_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_smart_turn_service_proto_goTypes = []any{
	(*SmartTurnRequest)(nil),  // 0: smart_turn.SmartTurnRequest
	(*SmartTurnResponse)(nil), // 1: smart_turn.SmartTurnResponse
}
var file_smart_turn_service_proto_depIdxs = []int32{
	0, // 0: smart_turn.SmartTurnServiceV1.Predict:input_type -> smart_turn.SmartTurnRequest
	1, // 1: smart_turn.SmartTurnServiceV1.Predict:output_type -> smart_turn.SmartTurnResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smart_turn_service_proto_init() }
func file_smart_turn_service_proto_init() {
	if File_smart_turn_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smart_turn_service_proto_rawDesc), len(file_smart_turn_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smart_turn_service_proto_goTypes,
		DependencyIndexes: file_smart_turn_service_proto_depIdxs,
		MessageInfos:      file_smart_turn_service_proto_msgTypes,
	}.Build()
	File_smart_turn_service_proto = out.File
	file_smart_turn_service_proto_goTypes = nil
	file_smart_turn_service_proto_depIdxs = nil
}
